name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Test FirstSentence
      id: test-firstsentence
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test FirstSentence
        setup-command: ''
        command: 'sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog22Test.testFirstSentence" '
        timeout: 10
        max-score: 7
    - name: Test SecondSentence
      id: test-secondsentence
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test SecondSentence
        setup-command: ''
        command: 'sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog22Test.testSecondSentence" '
        timeout: 10
        max-score: 6
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-FIRSTSENTENCE_RESULTS: "${{steps.test-firstsentence.outputs.result}}"
        TEST-SECONDSENTENCE_RESULTS: "${{steps.test-secondsentence.outputs.result}}"
      with:
        runners: test-firstsentence,test-secondsentence
